### ISSUE TITLE
Cart

### ISSUE THREAD

**Issue by LawreenL** [anandimous/DAM#105]
**User Story**
   As a logged-in Client, I want to:
- Add multiple items to my cart

**Acceptance Test**
   Given that I am a logged-in Client, when I:
- Click on "add to cart" in the details page of an item, it should be added to my cart
- Click on "remove from cart" on the cart page, it should be removed from my cart

**Comment by lawzeem** [comment]
We are not doing this for this sprint. We felt that a one button click reserve for logged in users would be more convenient for users so we decided to go with that route.
