### ISSUE TITLE
Email Confirmation [new user]

### ISSUE THREAD

**Issue by LawreenL** [anandimous/DAM#106]
**User Story**
As a Client creating an account, I want to:
- confirm my email when verifying my account

**Acceptance Test**
Given that I am a new Client, when I:
- create an account, I should get an email in my associated email
- be able to verify that email and receive confirmation

**Comment by lawzeem** [comment]
We are not doing this for this sprint. We have added the feature for Clients to create accounts. For now we decided not to work on this issue.
