### ISSUE TITLE
Email Confirmation [Item Reservation for non-logged in/no account clients]

### ISSUE THREAD

**Issue by LawreenL** [anandimous/DAM#107]
**User Story**
As a Client without an account/not logged-in, I want to:
- confirm my email when reserving an item

**Acceptance Test**
Given that I am not logged-in or do not have an account, when I
- reserve an Item, I should get an email to verify my reservation
- be able to verify my reservation and receive confirmation

**Comment by lawzeem** [comment]
We are not doing this. Users must log in to reserve items. We have added the functionality to create accounts.
