### ISSUE TITLE
Create Static Files

### ISSUE THREAD

**Issue by LawreenL** [anandimous/DAM#51]
*Task:*
- Create a set of static CSS files that can be used in all templates

*Test:*
- Able to access static files and use them

**Comment by StephenOrJames** [comment]
@lawzeem is this done?

**Comment by lawzeem** [comment]
> @lawzeem is this done?

This is done. In the pull request I made, I added it to the Static folder. (#60)

**Comment by StephenOrJames** [comment]
In that case, I'd rather leave this open until it's merged in. You could possibly leave a message on your PR that says `Fixes #51`, for example, that would auto-close this issue when it is merged.
